## Nonlinear Model Predicitive Control Parameters
chain_base_link: base_link
chain_tip_link: arm_right_7_link
root_frame: odom_combined

## joint_names
joint_names: [arm_right_1_joint, arm_right_2_joint, arm_right_3_joint, arm_right_4_joint, arm_right_5_joint, arm_right_6_joint, arm_right_7_joint]

nmpc:
  state_dim: 10
  control_dim: 10
  time_horizon: 0.5
  shooting_nodes: 5
  
  base:
    base_active: true

  constraints:
    state:
      path_constraints:
        min: [-999, -999, -999, -4, -1.92, -2.967, -2.618, -2.967, -2.443, -2.967]
        max: [ 999,  999,  999,  4,  1.92,  2.967,  2.618,  2.967,  2.443,  2.967]
      terminal_constraints:
        min: [-999, -999, -999, -4, -1.92, -2.967, -2.618, -2.967, -2.443, -2.967]
        max: [ 999,  999,  999,  4,  1.92,  2.967,  2.618,  2.967,  2.443,  2.967]
    input:
      input_constraints:
        min: [-0.3, -0.3, -1, -1, -1, -1, -1, -1, -1, -1]
        max: [ 0.3,  0.3,  1,  1,  1,  1,  1,  1,  1,  1]
    min_distance: 0.15
