## The following parameter structure defines what pairs of links are to be considered during self-collision avoidance

## Left: The link that is considered an 'obstacle' during self-collision avoidance
## Right: The links of the component that are to be checked for self-collision with the 'obstacle'
self_collision_matrix: {
    arm_left_7_link : [arm_left_3_link],
    arm_left_5_link : [],
    arm_left_3_link : [],
    body : [arm_left_3_link, arm_left_5_link, arm_left_7_link],
}

## Only for base. Values shift the BV up the z axis
bounding_volume_base : {
    position : [0.2, 0.4, 0.6, 0.8, 1.0, 1.25],
    bv_radius : [0.35, 0.25, 0.2, 0.2, 0.2, 0.25],
}

