## Nonlinear Model Predicitive Control Parameters
chain_base_link: arm_podest_link
chain_tip_link: arm_7_link
root_frame: world

## joint_names
joint_names: [arm_1_joint, arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint, arm_6_joint, arm_7_joint]

nmpc:
  state_dim: 7
  control_dim: 7
  time_horizon: 0.5
  shooting_nodes: 5
  
  base:
    base_active: false

  constraints:
    state:
      path_constraints:
        min: [-4, -1.92, -2.967, -2.618, -2.967, -2.443, -2.967]
        max: [ 4,  1.92,  2.967,  2.618,  2.967,  2.443,  2.967]
      terminal_constraints:
        min: [-4, -1.92, -2.967, -2.618, -2.967, -2.443, -2.967]
        max: [ 4,  1.92,  2.967,  2.618,  2.967,  2.443,  2.967]
    input:
      input_constraints:
        min: [-1, -1, -1, -1, -1, -1, -1]
        max: [ 1,  1,  1,  1,  1,  1,  1]
    min_distance: 0.15
