## Nonlinear Model Predicitive Control Parameters
chain_base_link: arm_podest_link
chain_tip_link: arm_7_link
root_frame: world

## joint_names
joint_names: [arm_1_joint, arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint, arm_6_joint, arm_7_joint]

nmpc:
  state_dim: 7
  control_dim: 7
  time_horizon: 0.5
  shooting_nodes: 5
  
  base:
    base_active: false

  constraints:
    state:
      path_constraints:
        min: [-3.8, -1.8, -2.8, -2.5, -2.8, -2.3, -2.8]
        max: [ 3.8,  1.8,  2.8,  2.5,  2.8,  2.3,  2.8]
      terminal_constraints:
        min: [-3.8, -1.8, -2.8, -2.5, -2.8, -2.3, -2.8]
        max: [ 3.8,  1.8,  2.8,  2.5,  2.8,  2.3,  2.8]
    input:
      input_constraints:
        min: [-0.6,-1.57 ,-1.57 ,-1.57 ,-1.57 ,-2.09 ,-2.09]
        max: [ 0.6, 1.57 , 1.57 ,1.57  ,1.57  , 2.09 ,2.09]
    min_distance: 0.15
