## Nonlinear Model Predicitive Control Parameters
chain_base_link: arm_base_link
chain_tip_link: arm_7_link
root_frame: world

nmpc:
  state_dim: 7
  control_dim: 7
  time_horizon: 0.6
  shooting_nodes: 6
  
  #Denavit Hartenberg Parameters (theta, d, a, alpha)
  transformations: ['T1','T2','T3','T4','T5','T6','T7']
  dh:
    T1: {theta: 'x(0)', d: 0.2815, a: 0.0, alpha:  1.5708}
    T2: {theta: 'x(1)', d: 0.0,    a: 0.0, alpha: -1.5708}
    T3: {theta: 'x(2)', d: 0.4536, a: 0.0, alpha:  1.5708}
    T4: {theta: 'x(3)', d: 0.0,    a: 0.0, alpha: -1.5708}
    T5: {theta: 'x(4)', d: 0.2986, a: 0.0, alpha:  1.5708}
    T6: {theta: 'x(5)', d: 0.0,    a: 0.0, alpha: -1.5708}
    T7: {theta: 'x(6)', d: 0.0,    a: 0.0, alpha:  0.0}

  constraints:
    state:
      path_constraints:
        min: [-4.712, -1.92, -2.967, -2.618, -2.967, -2.443, -2.967]
        max: [4.712,  1.92,  2.967,  2.618,  2.967,  2.443,  2.967]
      terminal_constraints:
        min: [-4.712, -1.92, -2.967, -2.618, -2.967, -2.443, -2.967]
        max: [4.712,  1.92,  2.967,  2.618,  2.967,  2.443,  2.967]
    input:
      input_constraints:
        min: [ -1, -1, -1, -1, -1, -1, -1]
        max: [  1,  1,  1,  1,  1,  1,  1]

