## Nonlinear Model Predicitive Control Parameters
chain_base_link: base_footprint
chain_tip_link: gripper_link
root_frame: odom_combined

## joint_names
joint_names: [prismatic1, joint1, joint2, gripper_joint]

nmpc:
  state_dim: 7
  control_dim: 7
  time_horizon: 0.5
  shooting_nodes: 5
  
  base:
    base_active: true

  constraints:
    state:
      path_constraints:
        min: [-999, -999, -999, -4, -1.92, -2.967, -2.618]
        max: [ 999,  999,  999,  4,  1.92,  2.967,  2.618]
      terminal_constraints:
        min: [-999, -999, -999, -4, -1.92, -2.967, -2.618]
        max: [ 999,  999,  999,  4,  1.92,  2.967,  2.618]
    input:
      input_constraints:
        min: [-0.3, -0.3, -1, -1, -1, -1, -1]
        max: [ 0.3,  0.3,  1,  1,  1,  1,  1]
    min_distance: 0.15
